### ISSUE TITLE
Realtek Semiconductor Corp.

### ISSUE THREAD

**Issue by EthelEleanor** [justinmchase/Clipboard#3]
What dose this mean 5/16/2016 4:22:18 AM
Device HDAUDIO\FUNC_01&VEN_10EC&DEV_0662&SUBSYS_103C2B28&REV_1003\4&39c081d3&0&0001 was migrated.

Last Device Instance Id: HDAUDIO\FUNC_01&VEN_10EC&DEV_0662&SUBSYS_103C2B28&REV_1003\4&39c081d3&0&0001
Class Guid: {4D36E96C-E325-11CE-BFC1-08002BE10318}
Location Path: 
Migration Rank: 0x0
Present: true

**Comment by justinmchase** [comment]
Why are you seeing that? It looks like you had a hardware failure.
