### ISSUE TITLE
Still not always working

### ISSUE THREAD

**Issue by Hexaae** [justinmchase/Clipboard#4]
Windows 10 x64 Anniversary Update (1607, 14393.51) here.

Sometimes randomly still fails to transfer UWP-clipboard to desktop-clipboard with an error message.

**Comment by justinmchase** [comment]
What is the error message? How can I reproduce it?

**Comment by Hexaae** [comment]
It happens randomly unfortunately... The tools from which I use Clipboard most are Edge (Make a Web note) and OneDrive UWP app from MS Store.
If you send me a debug version with a log output I could track down the error for you when it happens. Not sure if it's possible with UWP though...

**Comment by justinmchase** [comment]
Unfortunately you have to build it from code to get a debug version, the tools are required to load debug apps. The code is here in this repo and I can give you instructions on how to do it if you want.

**Comment by Hexaae** [comment]
Still randomly happens :(
No problem with "Share to Clipboard" or "Send to Clipboard" apps, so it must be something unreliable in the code...
