### ISSUE TITLE
Não entendo a aplicação clipbord da loja da microsoft

### ISSUE THREAD

**Issue by cradino** [justinmchase/Clipboard#5]
Afinal a clipboard da microsoft é open source?

**Comment by cradino** [comment]
Não me parece que me evite instalar a clipmate da tornsoft

**Comment by justinmchase** [comment]
Este é um app de festa 3 que vive na loja de app de Microsoft, não um produto oficial da Microsoft. É útil para a ponte entre a área de trabalho da área de transferência e o novo sistema de compartilhamento no Windows.

No entanto é fonte aberta! Deixe-me saber se você tem qualquer problema.

Traduzido por [bing] (http://www.bing.com/translator) o seguinte:
> This is a 3rd party app that lives on the Microsoft app store, not an official Microsoft product. It is useful for bridging between the desktop Clipboard and the new Share system in Windows.

> It is open source though! Let me know if you have any issues.

**Comment by cradino** [comment]
Poderia ajudar-me a perceber a função dessa aplicação um video ou tutorial
Cumprimentos
Arcindo lucas
P.s.
Eu uso em alternativa a area de transfetencia do windows a aplicação paga
clipmate da torsoft

Em 02/12/2016 17:31, "Justin Chase" <notifications@github.com> escreveu:
